#include "errors.h"

const char* error_msg[] = {
		MSG_OK,
		MSG_ERROR_NULL_POINTER,
		MSG_ERROR_INVALID_ARGUMENTS,
		MSG_ERROR_MEMORY_SHORTAGE,
		MSG_ERROR_SYS_TIME,
		MSG_ERROR_OPENING_FILE,
		MSG_ERROR_DISK_SPACE,
		MSG_ERROR_MISSING_FILE,
		MSG_ERROR_INVALID_OPERATION,
 		MSG_ERROR_UNSUPPORTED_CONTENT_TYPE,  
 		MSG_ERROR_INVALID_METHOD, 
 		MSG_ERROR_OPERATION_NOT_FOUND, 
 		MSG_ERROR_URL_NOT_FOUND,
 		MSG_ERROR_HOST_NOT_FOUND,
 		MSG_ERROR_DATA_NOT_FOUND,  
 		MSG_ERROR_CONTENT_TYPE_HEADER_NOT_FOUND, 
 		MSG_ERROR_INVALID_XML, 
		MSG_ERROR_MISSING_DATA,
		MSG_ERROR_OPERATION_FAILURE
	};

