#include "errors.h"

const char* error_msg[] = {
		MSG_OK,
		MSG_ERROR_NULL_POINTER,
		MSG_ERROR_INVALID_ARGUMENTS,
		MSG_ERROR_MEMORY_SHORTAGE,
		MSG_ERROR_SYS_TIME,
		MSG_ERROR_OPENING_FILE,
		MSG_ERROR_DISK_SPACE,
		MSG_ERROR_MISSING_FILE
	};

